// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ffxdkifwaxgaojlyppmg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZmeGRraWZ3YXhnYW9qbHlwcG1nIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzQzNDg2MzYsImV4cCI6MjA4OTkyNDYzNn0.8m_1HB9ZYCQeZayj46j7qMZR75NFjnVhGOkf_O01SV8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Create a storage adapter that works in both browser and non-browser environments
const getStorage = () => {
  if (typeof window !== 'undefined' && window.localStorage) {
    return localStorage;
  }
  // Fallback for non-browser environments
  return {
    getItem: () => null,
    setItem: () => {},
    removeItem: () => {},
  } as any;
};

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: getStorage(),
    persistSession: true,
    autoRefreshToken: true,
  }
});